const COUNTRIES=[
{"c":"af","n":"Afghanistan","r":"Asia","s":"Southern Asia"},
{"c":"ax","n":"Åland Islands","r":"Europe","s":"Northern Europe"},
{"c":"al","n":"Albania","r":"Europe","s":"Southeast Europe"},
{"c":"dz","n":"Algeria","r":"Africa","s":"Northern Africa"},
{"c":"as","n":"American Samoa","r":"Oceania","s":"Polynesia"},
{"c":"ad","n":"Andorra","r":"Europe","s":"Southern Europe"},
{"c":"ao","n":"Angola","r":"Africa","s":"Middle Africa"},
{"c":"ai","n":"Anguilla","r":"Americas","s":"Caribbean"},
{"c":"aq","n":"Antarctica","r":"Antarctica","s":""},
{"c":"ag","n":"Antigua and Barbuda","r":"Americas","s":"Caribbean"},
{"c":"ar","n":"Argentina","r":"Americas","s":"South America"},
{"c":"am","n":"Armenia","r":"Asia","s":"Western Asia"},
{"c":"aw","n":"Aruba","r":"Americas","s":"Caribbean"},
{"c":"au","n":"Australia","r":"Oceania","s":"Australia and New Zealand"},
{"c":"at","n":"Austria","r":"Europe","s":"Central Europe"},
{"c":"az","n":"Azerbaijan","r":"Asia","s":"Western Asia"},
{"c":"bs","n":"Bahamas","r":"Americas","s":"Caribbean"},
{"c":"bh","n":"Bahrain","r":"Asia","s":"Western Asia"},
{"c":"bd","n":"Bangladesh","r":"Asia","s":"Southern Asia"},
{"c":"bb","n":"Barbados","r":"Americas","s":"Caribbean"},
{"c":"by","n":"Belarus","r":"Europe","s":"Eastern Europe"},
{"c":"be","n":"Belgium","r":"Europe","s":"Western Europe"},
{"c":"bz","n":"Belize","r":"Americas","s":"Central America"},
{"c":"bj","n":"Benin","r":"Africa","s":"Western Africa"},
{"c":"bm","n":"Bermuda","r":"Americas","s":"North America"},
{"c":"bt","n":"Bhutan","r":"Asia","s":"Southern Asia"},
{"c":"bo","n":"Bolivia","r":"Americas","s":"South America"},
{"c":"ba","n":"Bosnia and Herzegovina","r":"Europe","s":"Southeast Europe"},
{"c":"bw","n":"Botswana","r":"Africa","s":"Southern Africa"},
{"c":"bv","n":"Bouvet Island","r":"Antarctica","s":""},
{"c":"br","n":"Brazil","r":"Americas","s":"South America"},
{"c":"io","n":"British Indian Ocean Territory","r":"Africa","s":"Eastern Africa"},
{"c":"vg","n":"British Virgin Islands","r":"Americas","s":"Caribbean"},
{"c":"bn","n":"Brunei","r":"Asia","s":"South-Eastern Asia"},
{"c":"bg","n":"Bulgaria","r":"Europe","s":"Southeast Europe"},
{"c":"bf","n":"Burkina Faso","r":"Africa","s":"Western Africa"},
{"c":"bi","n":"Burundi","r":"Africa","s":"Eastern Africa"},
{"c":"kh","n":"Cambodia","r":"Asia","s":"South-Eastern Asia"},
{"c":"cm","n":"Cameroon","r":"Africa","s":"Middle Africa"},
{"c":"ca","n":"Canada","r":"Americas","s":"North America"},
{"c":"cv","n":"Cape Verde","r":"Africa","s":"Western Africa"},
{"c":"bq","n":"Caribbean Netherlands","r":"Americas","s":"Caribbean"},
{"c":"ky","n":"Cayman Islands","r":"Americas","s":"Caribbean"},
{"c":"cf","n":"Central African Republic","r":"Africa","s":"Middle Africa"},
{"c":"td","n":"Chad","r":"Africa","s":"Middle Africa"},
{"c":"cl","n":"Chile","r":"Americas","s":"South America"},
{"c":"cn","n":"China","r":"Asia","s":"Eastern Asia"},
{"c":"cx","n":"Christmas Island","r":"Oceania","s":"Australia and New Zealand"},
{"c":"cc","n":"Cocos (Keeling) Islands","r":"Oceania","s":"Australia and New Zealand"},
{"c":"co","n":"Colombia","r":"Americas","s":"South America"},
{"c":"km","n":"Comoros","r":"Africa","s":"Eastern Africa"},
{"c":"cg","n":"Congo","r":"Africa","s":"Middle Africa"},
{"c":"ck","n":"Cook Islands","r":"Oceania","s":"Polynesia"},
{"c":"cr","n":"Costa Rica","r":"Americas","s":"Central America"},
{"c":"hr","n":"Croatia","r":"Europe","s":"Southeast Europe"},
{"c":"cu","n":"Cuba","r":"Americas","s":"Caribbean"},
{"c":"cw","n":"Curaçao","r":"Americas","s":"Caribbean"},
{"c":"cy","n":"Cyprus","r":"Europe","s":"Southern Europe"},
{"c":"cz","n":"Czechia","r":"Europe","s":"Central Europe"},
{"c":"dk","n":"Denmark","r":"Europe","s":"Northern Europe"},
{"c":"dj","n":"Djibouti","r":"Africa","s":"Eastern Africa"},
{"c":"dm","n":"Dominica","r":"Americas","s":"Caribbean"},
{"c":"do","n":"Dominican Republic","r":"Americas","s":"Caribbean"},
{"c":"cd","n":"DR Congo","r":"Africa","s":"Middle Africa"},
{"c":"ec","n":"Ecuador","r":"Americas","s":"South America"},
{"c":"eg","n":"Egypt","r":"Africa","s":"Northern Africa"},
{"c":"sv","n":"El Salvador","r":"Americas","s":"Central America"},
{"c":"gq","n":"Equatorial Guinea","r":"Africa","s":"Middle Africa"},
{"c":"er","n":"Eritrea","r":"Africa","s":"Eastern Africa"},
{"c":"ee","n":"Estonia","r":"Europe","s":"Northern Europe"},
{"c":"sz","n":"Eswatini","r":"Africa","s":"Southern Africa"},
{"c":"et","n":"Ethiopia","r":"Africa","s":"Eastern Africa"},
{"c":"fk","n":"Falkland Islands","r":"Americas","s":"South America"},
{"c":"fo","n":"Faroe Islands","r":"Europe","s":"Northern Europe"},
{"c":"fj","n":"Fiji","r":"Oceania","s":"Melanesia"},
{"c":"fi","n":"Finland","r":"Europe","s":"Northern Europe"},
{"c":"fr","n":"France","r":"Europe","s":"Western Europe"},
{"c":"gf","n":"French Guiana","r":"Americas","s":"South America"},
{"c":"pf","n":"French Polynesia","r":"Oceania","s":"Polynesia"},
{"c":"tf","n":"French Southern and Antarctic Lands","r":"Antarctica","s":""},
{"c":"ga","n":"Gabon","r":"Africa","s":"Middle Africa"},
{"c":"gm","n":"Gambia","r":"Africa","s":"Western Africa"},
{"c":"ge","n":"Georgia","r":"Asia","s":"Western Asia"},
{"c":"de","n":"Germany","r":"Europe","s":"Western Europe"},
{"c":"gh","n":"Ghana","r":"Africa","s":"Western Africa"},
{"c":"gi","n":"Gibraltar","r":"Europe","s":"Southern Europe"},
{"c":"gr","n":"Greece","r":"Europe","s":"Southern Europe"},
{"c":"gl","n":"Greenland","r":"Americas","s":"North America"},
{"c":"gd","n":"Grenada","r":"Americas","s":"Caribbean"},
{"c":"gp","n":"Guadeloupe","r":"Americas","s":"Caribbean"},
{"c":"gu","n":"Guam","r":"Oceania","s":"Micronesia"},
{"c":"gt","n":"Guatemala","r":"Americas","s":"Central America"},
{"c":"gg","n":"Guernsey","r":"Europe","s":"Northern Europe"},
{"c":"gn","n":"Guinea","r":"Africa","s":"Western Africa"},
{"c":"gw","n":"Guinea-Bissau","r":"Africa","s":"Western Africa"},
{"c":"gy","n":"Guyana","r":"Americas","s":"South America"},
{"c":"ht","n":"Haiti","r":"Americas","s":"Caribbean"},
{"c":"hm","n":"Heard Island and McDonald Islands","r":"Antarctica","s":""},
{"c":"hn","n":"Honduras","r":"Americas","s":"Central America"},
{"c":"hk","n":"Hong Kong","r":"Asia","s":"Eastern Asia"},
{"c":"hu","n":"Hungary","r":"Europe","s":"Central Europe"},
{"c":"is","n":"Iceland","r":"Europe","s":"Northern Europe"},
{"c":"in","n":"India","r":"Asia","s":"Southern Asia"},
{"c":"id","n":"Indonesia","r":"Asia","s":"South-Eastern Asia"},
{"c":"ir","n":"Iran","r":"Asia","s":"Southern Asia"},
{"c":"iq","n":"Iraq","r":"Asia","s":"Western Asia"},
{"c":"ie","n":"Ireland","r":"Europe","s":"Northern Europe"},
{"c":"im","n":"Isle of Man","r":"Europe","s":"Northern Europe"},
{"c":"il","n":"Israel","r":"Asia","s":"Western Asia"},
{"c":"it","n":"Italy","r":"Europe","s":"Southern Europe"},
{"c":"ci","n":"Ivory Coast","r":"Africa","s":"Western Africa"},
{"c":"jm","n":"Jamaica","r":"Americas","s":"Caribbean"},
{"c":"jp","n":"Japan","r":"Asia","s":"Eastern Asia"},
{"c":"je","n":"Jersey","r":"Europe","s":"Northern Europe"},
{"c":"jo","n":"Jordan","r":"Asia","s":"Western Asia"},
{"c":"kz","n":"Kazakhstan","r":"Asia","s":"Central Asia"},
{"c":"ke","n":"Kenya","r":"Africa","s":"Eastern Africa"},
{"c":"ki","n":"Kiribati","r":"Oceania","s":"Micronesia"},
{"c":"xk","n":"Kosovo","r":"Europe","s":"Southeast Europe"},
{"c":"kw","n":"Kuwait","r":"Asia","s":"Western Asia"},
{"c":"kg","n":"Kyrgyzstan","r":"Asia","s":"Central Asia"},
{"c":"la","n":"Laos","r":"Asia","s":"South-Eastern Asia"},
{"c":"lv","n":"Latvia","r":"Europe","s":"Northern Europe"},
{"c":"lb","n":"Lebanon","r":"Asia","s":"Western Asia"},
{"c":"ls","n":"Lesotho","r":"Africa","s":"Southern Africa"},
{"c":"lr","n":"Liberia","r":"Africa","s":"Western Africa"},
{"c":"ly","n":"Libya","r":"Africa","s":"Northern Africa"},
{"c":"li","n":"Liechtenstein","r":"Europe","s":"Western Europe"},
{"c":"lt","n":"Lithuania","r":"Europe","s":"Northern Europe"},
{"c":"lu","n":"Luxembourg","r":"Europe","s":"Western Europe"},
{"c":"mo","n":"Macau","r":"Asia","s":"Eastern Asia"},
{"c":"mg","n":"Madagascar","r":"Africa","s":"Eastern Africa"},
{"c":"mw","n":"Malawi","r":"Africa","s":"Eastern Africa"},
{"c":"my","n":"Malaysia","r":"Asia","s":"South-Eastern Asia"},
{"c":"mv","n":"Maldives","r":"Asia","s":"Southern Asia"},
{"c":"ml","n":"Mali","r":"Africa","s":"Western Africa"},
{"c":"mt","n":"Malta","r":"Europe","s":"Southern Europe"},
{"c":"mh","n":"Marshall Islands","r":"Oceania","s":"Micronesia"},
{"c":"mq","n":"Martinique","r":"Americas","s":"Caribbean"},
{"c":"mr","n":"Mauritania","r":"Africa","s":"Western Africa"},
{"c":"mu","n":"Mauritius","r":"Africa","s":"Eastern Africa"},
{"c":"yt","n":"Mayotte","r":"Africa","s":"Eastern Africa"},
{"c":"mx","n":"Mexico","r":"Americas","s":"North America"},
{"c":"fm","n":"Micronesia","r":"Oceania","s":"Micronesia"},
{"c":"md","n":"Moldova","r":"Europe","s":"Eastern Europe"},
{"c":"mc","n":"Monaco","r":"Europe","s":"Western Europe"},
{"c":"mn","n":"Mongolia","r":"Asia","s":"Eastern Asia"},
{"c":"me","n":"Montenegro","r":"Europe","s":"Southeast Europe"},
{"c":"ms","n":"Montserrat","r":"Americas","s":"Caribbean"},
{"c":"ma","n":"Morocco","r":"Africa","s":"Northern Africa"},
{"c":"mz","n":"Mozambique","r":"Africa","s":"Eastern Africa"},
{"c":"mm","n":"Myanmar","r":"Asia","s":"South-Eastern Asia"},
{"c":"na","n":"Namibia","r":"Africa","s":"Southern Africa"},
{"c":"nr","n":"Nauru","r":"Oceania","s":"Micronesia"},
{"c":"np","n":"Nepal","r":"Asia","s":"Southern Asia"},
{"c":"nl","n":"Netherlands","r":"Europe","s":"Western Europe"},
{"c":"nc","n":"New Caledonia","r":"Oceania","s":"Melanesia"},
{"c":"nz","n":"New Zealand","r":"Oceania","s":"Australia and New Zealand"},
{"c":"ni","n":"Nicaragua","r":"Americas","s":"Central America"},
{"c":"ne","n":"Niger","r":"Africa","s":"Western Africa"},
{"c":"ng","n":"Nigeria","r":"Africa","s":"Western Africa"},
{"c":"nu","n":"Niue","r":"Oceania","s":"Polynesia"},
{"c":"nf","n":"Norfolk Island","r":"Oceania","s":"Australia and New Zealand"},
{"c":"kp","n":"North Korea","r":"Asia","s":"Eastern Asia"},
{"c":"mk","n":"North Macedonia","r":"Europe","s":"Southeast Europe"},
{"c":"mp","n":"Northern Mariana Islands","r":"Oceania","s":"Micronesia"},
{"c":"no","n":"Norway","r":"Europe","s":"Northern Europe"},
{"c":"om","n":"Oman","r":"Asia","s":"Western Asia"},
{"c":"pk","n":"Pakistan","r":"Asia","s":"Southern Asia"},
{"c":"pw","n":"Palau","r":"Oceania","s":"Micronesia"},
{"c":"ps","n":"Palestine","r":"Asia","s":"Western Asia"},
{"c":"pa","n":"Panama","r":"Americas","s":"Central America"},
{"c":"pg","n":"Papua New Guinea","r":"Oceania","s":"Melanesia"},
{"c":"py","n":"Paraguay","r":"Americas","s":"South America"},
{"c":"pe","n":"Peru","r":"Americas","s":"South America"},
{"c":"ph","n":"Philippines","r":"Asia","s":"South-Eastern Asia"},
{"c":"pn","n":"Pitcairn Islands","r":"Oceania","s":"Polynesia"},
{"c":"pl","n":"Poland","r":"Europe","s":"Central Europe"},
{"c":"pt","n":"Portugal","r":"Europe","s":"Southern Europe"},
{"c":"pr","n":"Puerto Rico","r":"Americas","s":"Caribbean"},
{"c":"qa","n":"Qatar","r":"Asia","s":"Western Asia"},
{"c":"re","n":"Réunion","r":"Africa","s":"Eastern Africa"},
{"c":"ro","n":"Romania","r":"Europe","s":"Southeast Europe"},
{"c":"ru","n":"Russia","r":"Europe","s":"Eastern Europe"},
{"c":"rw","n":"Rwanda","r":"Africa","s":"Eastern Africa"},
{"c":"bl","n":"Saint Barthélemy","r":"Americas","s":"Caribbean"},
{"c":"sh","n":"Saint Helena, Ascension and Tristan da Cunha","r":"Africa","s":"Western Africa"},
{"c":"kn","n":"Saint Kitts and Nevis","r":"Americas","s":"Caribbean"},
{"c":"lc","n":"Saint Lucia","r":"Americas","s":"Caribbean"},
{"c":"mf","n":"Saint Martin","r":"Americas","s":"Caribbean"},
{"c":"pm","n":"Saint Pierre and Miquelon","r":"Americas","s":"North America"},
{"c":"vc","n":"Saint Vincent and the Grenadines","r":"Americas","s":"Caribbean"},
{"c":"ws","n":"Samoa","r":"Oceania","s":"Polynesia"},
{"c":"sm","n":"San Marino","r":"Europe","s":"Southern Europe"},
{"c":"st","n":"São Tomé and Príncipe","r":"Africa","s":"Middle Africa"},
{"c":"sa","n":"Saudi Arabia","r":"Asia","s":"Western Asia"},
{"c":"sn","n":"Senegal","r":"Africa","s":"Western Africa"},
{"c":"rs","n":"Serbia","r":"Europe","s":"Southeast Europe"},
{"c":"sc","n":"Seychelles","r":"Africa","s":"Eastern Africa"},
{"c":"sl","n":"Sierra Leone","r":"Africa","s":"Western Africa"},
{"c":"sg","n":"Singapore","r":"Asia","s":"South-Eastern Asia"},
{"c":"sx","n":"Sint Maarten","r":"Americas","s":"Caribbean"},
{"c":"sk","n":"Slovakia","r":"Europe","s":"Central Europe"},
{"c":"si","n":"Slovenia","r":"Europe","s":"Central Europe"},
{"c":"sb","n":"Solomon Islands","r":"Oceania","s":"Melanesia"},
{"c":"so","n":"Somalia","r":"Africa","s":"Eastern Africa"},
{"c":"za","n":"South Africa","r":"Africa","s":"Southern Africa"},
{"c":"gs","n":"South Georgia","r":"Antarctica","s":""},
{"c":"kr","n":"South Korea","r":"Asia","s":"Eastern Asia"},
{"c":"ss","n":"South Sudan","r":"Africa","s":"Middle Africa"},
{"c":"es","n":"Spain","r":"Europe","s":"Southern Europe"},
{"c":"lk","n":"Sri Lanka","r":"Asia","s":"Southern Asia"},
{"c":"sd","n":"Sudan","r":"Africa","s":"Northern Africa"},
{"c":"sr","n":"Suriname","r":"Americas","s":"South America"},
{"c":"sj","n":"Svalbard and Jan Mayen","r":"Europe","s":"Northern Europe"},
{"c":"se","n":"Sweden","r":"Europe","s":"Northern Europe"},
{"c":"ch","n":"Switzerland","r":"Europe","s":"Western Europe"},
{"c":"sy","n":"Syria","r":"Asia","s":"Western Asia"},
{"c":"tw","n":"Taiwan","r":"Asia","s":"Eastern Asia"},
{"c":"tj","n":"Tajikistan","r":"Asia","s":"Central Asia"},
{"c":"tz","n":"Tanzania","r":"Africa","s":"Eastern Africa"},
{"c":"th","n":"Thailand","r":"Asia","s":"South-Eastern Asia"},
{"c":"tl","n":"Timor-Leste","r":"Asia","s":"South-Eastern Asia"},
{"c":"tg","n":"Togo","r":"Africa","s":"Western Africa"},
{"c":"tk","n":"Tokelau","r":"Oceania","s":"Polynesia"},
{"c":"to","n":"Tonga","r":"Oceania","s":"Polynesia"},
{"c":"tt","n":"Trinidad and Tobago","r":"Americas","s":"Caribbean"},
{"c":"tn","n":"Tunisia","r":"Africa","s":"Northern Africa"},
{"c":"tr","n":"Türkiye","r":"Asia","s":"Western Asia"},
{"c":"tm","n":"Turkmenistan","r":"Asia","s":"Central Asia"},
{"c":"tc","n":"Turks and Caicos Islands","r":"Americas","s":"Caribbean"},
{"c":"tv","n":"Tuvalu","r":"Oceania","s":"Polynesia"},
{"c":"ug","n":"Uganda","r":"Africa","s":"Eastern Africa"},
{"c":"ua","n":"Ukraine","r":"Europe","s":"Eastern Europe"},
{"c":"ae","n":"United Arab Emirates","r":"Asia","s":"Western Asia"},
{"c":"gb","n":"United Kingdom","r":"Europe","s":"Northern Europe"},
{"c":"us","n":"United States","r":"Americas","s":"North America"},
{"c":"um","n":"United States Minor Outlying Islands","r":"Americas","s":"North America"},
{"c":"vi","n":"United States Virgin Islands","r":"Americas","s":"Caribbean"},
{"c":"uy","n":"Uruguay","r":"Americas","s":"South America"},
{"c":"uz","n":"Uzbekistan","r":"Asia","s":"Central Asia"},
{"c":"vu","n":"Vanuatu","r":"Oceania","s":"Melanesia"},
{"c":"va","n":"Vatican City","r":"Europe","s":"Southern Europe"},
{"c":"ve","n":"Venezuela","r":"Americas","s":"South America"},
{"c":"vn","n":"Vietnam","r":"Asia","s":"South-Eastern Asia"},
{"c":"wf","n":"Wallis and Futuna","r":"Oceania","s":"Polynesia"},
{"c":"eh","n":"Western Sahara","r":"Africa","s":"Northern Africa"},
{"c":"ye","n":"Yemen","r":"Asia","s":"Western Asia"},
{"c":"zm","n":"Zambia","r":"Africa","s":"Eastern Africa"},
{"c":"zw","n":"Zimbabwe","r":"Africa","s":"Eastern Africa"},
];
export const REGIONS=["Asia","Europe","Africa","Oceania","Americas","Antarctica"];
export { COUNTRIES };
