export const TIDBITS = {
  af: 'The emblem shows a mosque facing Mecca, wrapped in a wheat wreath.',
  ax: 'Aland belongs to Finland but speaks Swedish — its cross flag dates to 1954.',
  al: 'Albania is the "Land of the Eagles" — that is a double-headed eagle.',
  dz: 'The crescent and star honor its Muslim heritage; green is nature, white is peace.',
  as: 'The bald eagle clutches a fly whisk and staff from Samoan chiefs tradition.',
  ad: 'Its motto reads "Virtus Unita Fortior" — united virtue is stronger.',
  ao: 'The machete crossed with a gear honors the workers and farmers.',
  ai: 'Three golden dolphins leap in a circle — friendship and strength.',
  aq: 'No country owns Antarctica — a 1959 treaty keeps it peaceful for everyone.',
  ag: 'The rising sun has 7 points — six parishes plus the island of Barbuda.',
  ar: 'The Sun of May has a FACE — it honors the Inca sun god Inti.',
  am: 'The red, blue and orange were chosen back in 1918, its first independence.',
  aw: 'The red four-pointed star is Aruba itself; the stripes are its waves.',
  au: 'The Southern Cross constellation plus a star for its six states.',
  at: 'Legend says the white strip appeared where Duke Leopold bloodied his tunic.',
  az: 'Azerbaijan means "Land of Fire" — eight star points for eight Turkic peoples.',
  bs: 'Aquamarine stripes for the sea; the black triangle is the strength of the people.',
  bh: 'The five points of the star stand for the five pillars of Islam.',
  bd: 'Green is the land, the red disc is the sun rising over Bengal.',
  bb: 'The trident is BROKEN — a nod to independence from Britain in 1966.',
  by: 'One of few flags with an embroidered folk-pattern stripe down the side.',
  be: 'The colors come from the medieval lion of Brabant, styled after France.',
  bz: 'The only flag with HUMANS on it — two woodcutters flank a mahogany tree.',
  bj: 'The pan-African colors of hope — reborn as a democracy in 1990.',
  bm: 'The arms show the shipwreck of the Sea Venture, which founded Bermuda in 1609.',
  bt: 'The Druk — the Thunder Dragon — roars across the flag of Bhutan.',
  bo: 'Red for bravery, green for fertile land, yellow for its minerals.',
  bv: 'A lonely glacier-covered volcano island — home to seabirds and seals, nobody else.',
  ba: 'The triangle has three sides for three peoples; the stars mean Europe.',
  bw: 'The black-and-white stripes honor the zebra and harmony between people.',
  br: '27 stars map the sky over Rio on the night the republic was born.',
  io: 'Wavy blue and white lines for the Indian Ocean; a palm for its islands.',
  vg: 'Named for Saint Ursula and her 11,000 virgins — five lamps on the arms.',
  bn: 'The yellow is the sultan; the parasol and wings are royal symbols.',
  bg: 'White means freedom, green means the harvest, red means courage.',
  bf: 'The red star marks its mineral wealth — chosen by Sankara in 1984.',
  bi: 'Three six-pointed stars for its three communities living side by side.',
  kh: 'The ONLY national flag showing a real building — Angkor Wat.',
  cm: 'One central star for unity in the pan-African stripes.',
  ca: 'The maple leaf became a symbol in the 1800s; the flag itself is young (1965).',
  cv: 'Ten stars in a circle for its ten main islands.',
  bq: 'The white compass honors Bonaire sailors; the red star is the island.',
  ky: 'Three golden stars for three islands, plus a turtle and a pineapple.',
  cf: 'Four colors of old French Africa, crossed by red for the blood that united them.',
  td: 'Made to look like Romania on purpose — but with a darker night-blue.',
  cl: 'The Lone Star on red — Texas may have copied Chile for its own flag.',
  cn: 'One big star for the Party; four smaller stars for the people around it.',
  cx: 'A golden bosunbird flies over a silver disc — the island and its wildlife.',
  cc: 'A crescent for its Malay Muslim people, a palm tree for Cocos.',
  co: 'Its yellow stripe takes HALF the flag — twice every other stripe.',
  km: 'Four stars and four stripes for its four islands.',
  cg: 'Green for the forests, yellow for friendship, red for the struggle.',
  ck: '15 stars in a ring — the 15 islands, like a necklace.',
  cr: 'Blue-white-red adopted in 1848; red honors those who defended it.',
  hr: 'The checkerboard "šahovnica" shield dates back to medieval Croatian kings.',
  cu: 'Designed by a poet in 1849 — the triangle holds liberty, equality, fraternity.',
  cw: 'The two stars are Curaçao and its tiny neighbor Klein Curaçao.',
  cy: 'The ONLY flag showing its own map — with two olive branches for peace.',
  cz: 'The blue triangle was added so it would not look like Poland\'s flag.',
  dk: 'The OLDEST flag still flying — legend says it fell from the sky in 1219.',
  dj: 'Blue for the Issa, green for the Afar, red for the fight for freedom.',
  dm: 'Its Sisserou parrot makes it one of only TWO flags with purple.',
  do: 'Raised in 1844 after winning independence from Haiti.',
  cd: 'Six small stars for the six provinces of independence in 1960.',
  ec: 'The Andean CONDOR sits on top of Chimborazo volcano in the emblem.',
  eg: 'The Eagle of Saladin — named for the sultan who fought the crusaders.',
  sv: 'Five little flags in the arms remember the five United Provinces of Central America.',
  gq: 'The only national flag with its MOTTO printed on it: Unidad, Paz, Justicia.',
  er: 'The olive wreath is back from its 1952 flag — 30 years of war in the red stripe.',
  ee: 'Blue for the sky, black for the soil and hard history, white for snow and hope.',
  sz: 'The Nguni shield is protection; the spears and staff stand beside it.',
  et: 'Ethiopia is Africa\'s oldest independent nation; the pentagram unites all peoples.',
  fk: 'A ram for the sheep farms that shaped the Falklands.',
  fo: 'Designed by Faroese students in Copenhagen in 1919.',
  fj: 'Fiji debated dropping the Union Jack — the 2013 redesign kept it.',
  fi: 'Blue for its thousand lakes, white for snow; a Nordic cross.',
  fr: 'Born in the Revolution: white was royal, red and blue were Paris.',
  gf: 'Flies France\'s tricolor; its local flag carries a red star of unity.',
  pf: 'An outrigger canoe with five figures — one for each archipelago.',
  tf: 'No permanent people live here — five stars for five icy districts.',
  ga: 'Blue for the sea, yellow for the sun and savanna, green for forests.',
  gm: 'Red sun, blue river, green land — white lines for peace between.',
  ge: 'Five crosses echo medieval Georgian banners, revived in 2004.',
  de: 'Black-red-gold from the 1848 freedom movement — split East and West wore different flags.',
  gh: 'The black star honors Marcus Garvey — Ghana was the first colonized African nation to break free (1957).',
  gi: 'The castle and golden key on the arms were granted by a Spanish queen in 1502.',
  gr: 'Nine stripes for the nine syllables of "Freedom or Death".',
  gl: 'The disc is the sun setting over ice — half white, half red; drawn by a Greenlandic artist.',
  gd: 'A nutmeg berry sits by the flag — Grenada is the Isle of Spice.',
  gp: 'Flies France\'s tricolor; its local banner shows sugarcane and sunshine.',
  gu: 'The seal is shaped like a Chamorro slingstone, with a palm and a canoe.',
  gt: 'The QUETZAL bird — legend says it dies of sadness in captivity. A symbol of liberty.',
  gg: 'The gold cross dates to 1279, granted by the King of England.',
  gn: 'Red for labor, yellow for generosity, green for the land.',
  gw: 'The black star is Africa\'s star of freedom, like Ghana\'s.',
  gy: 'The "Golden Arrowhead" — each color names a part of Guyana\'s nature.',
  ht: 'Legend says Haiti made its flag by ripping the white stripe out of France\'s.',
  hm: 'An uninhabited volcano island — penguins outnumber people by millions.',
  hn: 'Five stars hoping the five old Central American nations unite again.',
  hk: 'The BAUHINIA flower — a hybrid magnolia named after a botanist governor.',
  hu: 'Red for strength, white for faithfulness, green for hope.',
  is: 'White is ice, blue is the sea, red is FIRE — volcanoes and lava.',
  in: 'The 24-spoke wheel comes from Emperor Ashoka\'s pillar, about 250 BC.',
  id: 'Red and white may trace all the way to 13th-century Majapahit banners.',
  ir: 'The emblem is a TULIP — also drawn as the word Allah in calligraphy.',
  iq: 'The green writing is the Takbir — "God is great" — in script.',
  ie: 'Green for Catholics, orange for Protestants, white for the peace between them.',
  im: 'Three joined legs, a symbol over 3,000 years old that also appears in Sicily.',
  il: 'Blue stripes copied from a prayer shawl; the Star of David added in 1891.',
  it: 'The tricolor came via Napoleon\'s France — green for the plains, or hope.',
  ci: 'It mirrors Ireland\'s flag — deliberately, said the designers.',
  jm: 'The only national flag with no red, white or blue at all!',
  jp: 'The "Hinomaru" sun disc is one of the oldest flag designs on Earth.',
  je: 'The three leopards come from the lions of Normandy, William the Conqueror\'s house.',
  jo: 'The seven-pointed star stands for the seven verses of the Quran\'s first chapter.',
  kz: 'A steppe eagle under a 32-ray sun; the border pattern is a Kazakh ornament of ram\'s horns.',
  ke: 'A Maasai SHIELD and two spears — defending freedom.',
  ki: 'A FRIGATEBIRD soars over a rising sun above the waves.',
  xk: 'Six white stars for Kosovo\'s six communities, on a blue like the EU\'s.',
  kw: 'From a poet\'s verse: swords\' blood, pure deeds, defeated enemies, fertile land.',
  kg: 'The sun has 40 rays for 40 tribes united by the hero Manas; the yellow marks a yurt\'s crown.',
  la: 'A full white moon over the Mekong — unity under the river.',
  lv: 'The dark red comes from a legend of a wounded chief wrapped in a white-striped bedsheet.',
  lb: 'The CEDAR — Bible-famous tree standing for holiness and eternity.',
  ls: 'The mokorotlo — a traditional Basotho hat — sits proudly in the middle.',
  lr: 'Liberia means "Land of the Free" — founded for freed American slaves, 11 stripes for 11 founders.',
  ly: 'Once flew ALL GREEN — the only single-color flag in modern history.',
  li: 'Liechtenstein added a crown after spotting an identical flag (Haiti\'s) at the 1936 Olympics.',
  lt: 'Yellow for amber and harvest, green for forests, red for blood of freedom.',
  lu: 'Its soft sky-blue exists only so nobody mixes it up with the Netherlands.',
  mo: 'A LOTUS rising over water, a bridge, and stars for its link to China.',
  mg: 'Red and white stripes echo an old kingdom; green is the hope of farmers.',
  mw: 'The rising SUN was dawn for all Africa — the 1964 design was restored in 2012.',
  my: '14 stripes for 13 states plus the capital; a crescent and a 14-point star.',
  mv: 'The crescent is Islam, green the palm trees, red the blood of heroes.',
  ml: 'Green-yellow-red — the pan-African trio that traces back to Ethiopia.',
  mt: 'The George Cross — awarded to the whole island for bravery in WWII.',
  mh: 'The widest standard flag shape (10:19); rays for its municipalities and districts.',
  mq: 'Flies France\'s tricolor; its historic snake flag is a local favorite.',
  mr: 'Two red side stripes were added in 2017 for blood shed for independence.',
  mu: 'Blue sea, red struggle, green cane fields, yellow light of independence.',
  yt: 'Mayotte\'s badge shows two SEAHORSES holding up a crescent.',
  mx: 'An eagle on a cactus eating a snake — the Aztec legend that founded Mexico City.',
  fm: 'Four stars for four states scattered across more than 600 islands.',
  md: 'Romania\'s stripes plus an eagle holding a cross, olive branch and scepter.',
  mc: 'The colors of the Grimaldi family — who have ruled Monaco since 1297.',
  mn: 'The soyombo emblem: fire, sun, moon — and two FISH, because fish never sleep.',
  me: 'The two-headed eagle and crown come from Montenegro\'s royal house.',
  ms: 'A SHAMROCK — Montserrat is the "Emerald Isle of the Caribbean".',
  ma: 'The green pentacle is the five pillars of Islam; red is the royal dynasty.',
  mz: 'The ONLY flag with a modern rifle — an AK-47 beside a hoe, a book and a star.',
  mm: 'One big white star for the union of its 14 states and regions.',
  na: 'The sun is life; red is heroism; blue sky meets Atlantic sea.',
  nr: 'A 12-pointed star for 12 tribes, sitting just below the Equator line.',
  np: 'The ONLY non-rectangular flag — a double triangle with sun and moon.',
  nl: 'The oldest tricolor — a "Prince\'s Flag" whose orange top slowly turned red.',
  nc: 'The totem-like arrow is a Kanak "flèche faîtière" from rooftop carvings.',
  nz: 'Four red stars — the Southern Cross as seen from New Zealand skies.',
  ni: 'Its emblem has a RAINBOW — one of only two flags with purple.',
  ne: 'Orange for the Sahara, white for purity, green for the pan-African spirit.',
  ng: 'Designed by a student, Taiwo Akinkunmi, in a 1959 contest; white lines are two rivers.',
  nu: 'Yellow for sunshine and warm feelings toward New Zealand.',
  nf: 'A PINE TREE — the island was settled by HMS Bounty mutineer descendants.',
  kp: 'The red star carries its revolutionary traditions, flag flying since 1948.',
  mk: 'A sun with eight wide rays — the "sun of liberty".',
  mp: 'A LATTE STONE — an ancient carved pillar — with a flower and star.',
  no: 'Its colors borrow from Denmark and Sweden — plus white for freedom.',
  om: 'The KHANJAR, a curved dagger, is the national emblem in the corner.',
  pk: 'The crescent means progress, the star light and knowledge; a white stripe for minorities.',
  pw: 'That is the MOON, not the sun — a full yellow moon rising on deep blue.',
  ps: 'The pan-Arab colors come from the banner of the 1916 Arab Revolt.',
  pa: 'Two stars for its two big political parties — one per half of the flag.',
  pg: 'A bird-of-paradise mid-mating-dance plus the Southern Cross — designed by a 15-year-old.',
  py: 'The ONLY flag with a different emblem on each side — lion and hat on the back.',
  pe: 'Legend says General San Martín chose the colors after spotting flamingos.',
  ph: 'Its 8-ray sun remembers eight first-revolt provinces — and in war, the flag flips upside down!',
  pn: 'The Bounty mutineers\' island — the shield shows a Bible and an anchor.',
  pl: 'A white eagle in a gold crown — from the legend of Lech and the sunset nest.',
  pt: 'An armillary sphere — the navigation tool of the Age of Discovery.',
  pr: 'The Cuban flag turned upside down — deliberately.',
  qa: 'Nine jagged points for the nine emirates of the old Trucial Coast.',
  re: 'Flies France\'s tricolor; local flags show its famous erupting volcano.',
  ro: 'Blue, yellow and red from the 1848 revolution.',
  ru: 'White, blue and red came from Peter the Great learning shipbuilding from the Dutch.',
  rw: 'A sun with 24 rays for enlightenment in the land of a thousand hills.',
  bl: 'Saint Barthélemy has a Swedish crown on its arms — it was Swedish for 90 years.',
  sh: 'Napoleon was exiled and died here; the arms show a ship and the wirebird.',
  kn: 'Two stars for two islands — Saint Kitts and Nevis.',
  lc: 'The twin PYRAMIDS are the Pitons, two volcanic spires rising from the sea.',
  mf: 'One island split between France and the Netherlands — the French side flies the tricolor.',
  pm: 'Three ships on the arms: Basque, Breton and Norman fishing boats.',
  vc: 'Three diamonds in a V — "the Gems of the Antilles".',
  ws: 'The SOUTHERN CROSS over blue sea, on red courage.',
  sm: 'Three towers on three peaks — San Marino is the world\'s oldest republic (301 AD).',
  st: 'Two stars for two tropical islands just north of the Equator.',
  sa: 'The flag carries the Islamic creed in script — so it is never lowered to half-mast.',
  sn: 'A green star of hope — green is also the Prophet\'s color.',
  rs: 'The two-headed eagle and crown come from medieval Serbian kings.',
  sc: 'Six rays fan out like the islands rising from the sea.',
  sl: 'Freetown was founded in 1792 as a home for freed slaves.',
  sg: 'Five stars mean democracy, peace, progress, justice and equality.',
  sx: 'The Dutch half of the split island — its arms show the border monument.',
  sk: 'A double cross on three hills — the cross of Cyril and Methodius.',
  si: 'Mount Triglav\'s three peaks, its rivers, and three stars of the Counts of Celje.',
  sb: 'Five stars for five island groups along a blue diagonal of ocean.',
  so: 'One five-pointed star for the five regions where Somalis live.',
  za: 'Six colors in a sideways Y — many peoples converging into one nation.',
  gs: 'Its coat of arms shows a lion, a reindeer AND two penguins.',
  kr: 'The taegeuk circle is balance; four trigrams stand for heaven, earth, water, fire.',
  ss: 'The world\'s newest widely recognized country — born in 2011.',
  es: 'The arms hold castles, lions, chains, a pomegranate and the Pillars of Hercules.',
  lk: 'A golden LION holding a sword — one of the world\'s oldest flag symbols.',
  sd: 'Pan-Arab stripes like Jordan\'s, with green for Islam and farming.',
  sr: 'A big yellow star unites the many peoples of Suriname.',
  sj: 'Polar bears outnumber people here — the flag is Norway\'s.',
  se: 'A yellow cross on blue — Christianity over Sweden\'s lakes and forests.',
  ch: 'One of only TWO square national flags — and the Red Cross symbol is its inverse.',
  sy: 'Two stars remember the 1958 union with Egypt.',
  tw: 'A white sun with 12 rays — progress through the hours of the day.',
  tj: '"Taj" means crown in Persian — so Tajikistan wears a crown and seven stars.',
  tz: 'Green land, black people, blue lakes and sea, yellow minerals — all joined by a diagonal.',
  th: 'Five stripes for nation, religion and monarchy.',
  tl: 'One of Asia\'s youngest countries (2002) — the yellow star guides the way.',
  tg: 'Five stripes for five regions; the star is life and purity.',
  tk: 'A canoe sail for the journey between its three atolls.',
  to: 'The only Pacific kingdom never colonized — its cross is Christianity.',
  tt: 'No emblem at all — just stripes for the people, the land and the sea.',
  tn: 'A crescent and star like Turkey\'s, but red for the blood of martyrs.',
  tr: 'The crescent and star in this exact form have flown since 1844.',
  tm: 'The stripe carries five CARPET patterns — one for each major Turkmen tribe.',
  tc: 'The badge shows a conch shell, a lobster and a cactus!',
  tv: 'Nine stars for nine islands — placed where Tuvalu really sits among the stars of the sky.',
  ug: 'The grey crowned CRANE lifts one leg — a bird that was never tamed.',
  ua: 'Blue sky over golden wheat fields.',
  ae: 'Seven emirates united as one country in 1971.',
  gb: 'Three flags merged into one Union Jack — England, Scotland and Ireland\'s crosses.',
  us: '50 stars, 13 stripes — and 27 different flag designs over its history.',
  um: 'No permanent residents — just reefs, atolls and the famous WWII airfield of Midway.',
  vi: 'V-I-S on a shield with palm, lily and a golden eagle.',
  uy: 'Nine stripes for nine departments; the Sun of May has a face and 16 rays.',
  uz: 'A crescent for rebirth and 12 stars for the months of the year.',
  vu: 'A BOAR\'S TUSK ring — a symbol of prosperity worn by local men.',
  va: 'The crossed KEYS of Saint Peter — and one of only two square flags.',
  ve: 'A white horse rears in the coat of arms — independence in motion.',
  vn: 'One star for five classes of people standing together.',
  wf: 'Three kings still share power with France — its local flag has four white triangles.',
  eh: 'The Sahrawi flag of Western Sahara carries pan-Arab colors with a crescent and star.',
  ye: 'Red-white-black pan-Arab stripes — the plain civil flag carries no emblem.',
  zm: 'A fish EAGLE rises above the stripes — freedom, and rising above challenges.',
  zw: 'The soapstone BIRD from Great Zimbabwe ruins, carved about 800 years ago.',
};
